version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: postgres_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - green_power

  mongo:
    image: mongo:latest
    container_name: mongo_db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    volumes:
      - mongodb_data:/data/db
    networks:
      - green_power

  redis:
    image: redis:7-alpine
    container_name: redis_broker
    ports:
      - "6369:6379"
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    volumes:
      - redis_data:/data
    networks:
      - green_power

  nginx:
    image: nginx:alpine
    container_name: green_power_nginx
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - green_power_backend_staticfiles:/green_power_backend/staticfiles
      - green_power_backend_mediafiles:/green_power_backend/mediafiles
    networks:
      - green_power
    depends_on:
      - green_power_backend

  green_power_backend:
    build: .
    container_name: green_power_backend
    expose:
      - 5000
    depends_on:
      - postgres
      - mongo
    environment:
      DJANGO_SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      DJANGO_ALLOWED_HOSTS: ${ALLOWED_HOSTS}
    env_file:
      - .env
    volumes:
      - green_power_backend_staticfiles:/green_power_backend/staticfiles
      - green_power_backend_mediafiles:/green_power_backend/mediafiles
    networks:
      - green_power

volumes:
  postgres_data:
  mongodb_data:
  redis_data:
  green_power_backend_staticfiles:
  green_power_backend_mediafiles:

networks:
  green_power:
    driver: bridge
