"""
Django settings for green_power_backend project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
import logging

# Load environment variables from .env into the system's environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY') or os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = [host.strip() for host in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if host.strip()]

REALTIME_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv("REALTIME_ALLOWED_ORIGINS", "").split(",")
    if origin.strip()
]

LOG_LEVEL = os.getenv('LOG_LEVEL', 'INFO').upper()
SUBSCRIBER_LOG_LEVEL = os.getenv('SUBSCRIBER_LOG_LEVEL', LOG_LEVEL).upper()


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'channels',
    'rest_framework',
    'drf_spectacular',

    'apps.grid.apps.GridConfig',
    'apps.generator.apps.GeneratorConfig',
    'apps.environment.apps.EnvironmentConfig',
    'apps.realtime.apps.RealtimeConfig',
    'apps.solar.apps.SolarConfig',
    'apps.ingestion.apps.IngestionConfig',
    'apps.api.apps.ApiConfig',
]

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Green Power API',
    'DESCRIPTION': 'REST API for environment, generator, grid, and solar data with time filters and aggregation.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

ASGI_APPLICATION = 'config.asgi.application'

# Channels Layer config (using Redis)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [(os.getenv('REDIS_HOST', '127.0.0.1'), int(os.getenv('REDIS_PORT', 6379)))]
        }
    }
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB_NAME', os.getenv('POSTGRES_DB', 'postgres')),
        'USER': os.getenv('POSTGRES_DB_USER', os.getenv('POSTGRES_USER', 'postgres')),
        'PASSWORD': os.getenv('POSTGRES_DB_PASSWORD', os.getenv('POSTGRES_PASSWORD', 'postgres')),
        'HOST': os.getenv('POSTGRES_DB_HOST', os.getenv('POSTGRES_HOST', 'localhost')),
        'PORT': os.getenv('POSTGRES_DB_PORT', os.getenv('POSTGRES_PORT', '5432')),
        'CONN_MAX_AGE': int(os.getenv('POSTGRES_CONN_MAX_AGE', '60')),
    }
}

# MongoDB configuration
MONGO_DB_HOST = os.getenv('MONGO_DB_HOST', os.getenv('MONGODB_HOST', 'localhost'))
MONGO_DB_PORT = os.getenv('MONGO_DB_PORT', os.getenv('MONGODB_PORT', '27017'))
MONGO_DB_NAME = os.getenv('MONGO_DB_NAME', os.getenv('MONGODB_NAME', 'test'))
MONGO_DB_USER = os.getenv('MONGO_DB_USER', os.getenv('MONGODB_USER'))
MONGO_DB_PASSWORD = os.getenv('MONGO_DB_PASSWORD', os.getenv('MONGODB_PASSWORD'))

MONGO_DB_URI = os.getenv('MONGO_DB_URI', os.getenv('MONGODB_URI'))
if not MONGO_DB_URI:
    if MONGO_DB_USER and MONGO_DB_PASSWORD:
        MONGO_DB_URI = (
            f"mongodb://{MONGO_DB_USER}:{MONGO_DB_PASSWORD}@{MONGO_DB_HOST}:{MONGO_DB_PORT}/?authSource=admin"
        )
    else:
        MONGO_DB_URI = f"mongodb://{MONGO_DB_HOST}:{MONGO_DB_PORT}"

MONGO_MAX_POOL_SIZE = int(os.getenv('MONGO_MAX_POOL_SIZE', '50'))
MONGO_MIN_POOL_SIZE = int(os.getenv('MONGO_MIN_POOL_SIZE', '0'))
MONGO_CONNECT_TIMEOUT_MS = int(os.getenv('MONGO_CONNECT_TIMEOUT_MS', '2000'))
MONGO_SOCKET_TIMEOUT_MS = int(os.getenv('MONGO_SOCKET_TIMEOUT_MS', '20000'))
MONGO_SERVER_SELECTION_TIMEOUT_MS = int(os.getenv('MONGO_SERVER_SELECTION_TIMEOUT_MS', '3000'))
MONGO_CREATE_INDEXES = os.getenv('MONGO_CREATE_INDEXES', 'true').lower() in ('true', '1', 'yes')


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True
SECURE_SSL_REDIRECT = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'  # URL to access static files

STATICFILES_DIRS = []
assets_dir = BASE_DIR / "assets"
if assets_dir.exists():
    STATICFILES_DIRS.append(assets_dir)

# Directory where Django will collect all static files to serve in production
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logger configuration
LOG_DIR = BASE_DIR / 'logs'
try:
    LOG_DIR.mkdir(parents=True, exist_ok=True)
except OSError:
    # Fallback to console-only logging if filesystem is read-only.
    pass

ENABLE_FILE_LOGS = LOG_DIR.exists() and os.access(LOG_DIR, os.W_OK)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'filters': {
        'only_info': {
            '()': 'django.utils.log.CallbackFilter',
            'callback': lambda record: record.levelno == logging.INFO,
        },
        'only_warning_and_above': {
            '()': 'django.utils.log.CallbackFilter',
            'callback': lambda record: record.levelno >= logging.WARNING,
        },
    },

    'formatters': {
        'standard': {
            'format': '[{asctime}] {levelname} {name} - {message}',
            'style': '{',
        },
    },

    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'level': LOG_LEVEL,
            'formatter': 'standard',
        },
        'info_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'info.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 10,
            'level': 'INFO',
            'filters': ['only_info'],
            'formatter': 'standard',
            'encoding': 'utf8',
        },
        'error_file': {
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': LOG_DIR / 'errors.log',
            'when': 'midnight',
            'backupCount': 10,
            'level': 'WARNING',
            'filters': ['only_warning_and_above'],
            'formatter': 'standard',
            'encoding': 'utf8',
        },
        'subscriber_error_file': {
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': LOG_DIR / 'subscriber_errors.log',
            'when': 'midnight',
            'backupCount': 7,
            'level': 'WARNING',
            'filters': ['only_warning_and_above'],
            'formatter': 'standard',
            'encoding': 'utf8',
        },
    },

    'loggers': {
        # Django core
        'django': {
            'handlers': ['console', 'info_file', 'error_file'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'django.request': {
            'handlers': ['error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['console', 'info_file', 'error_file'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['error_file'],
            'level': 'WARNING',
            'propagate': False,
        },

        # Project app-level loggers
        'config': {
            'handlers': ['console', 'info_file', 'error_file'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'subscriber': {
            'handlers': ['console', 'subscriber_error_file'],
            'level': SUBSCRIBER_LOG_LEVEL,
            'propagate': False,
        },

        # Catch-all
        '': {
            'handlers': ['console', 'info_file', 'error_file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

if not ENABLE_FILE_LOGS:
    for handler_name in ("info_file", "error_file", "subscriber_error_file"):
        LOGGING["handlers"].pop(handler_name, None)
    for logger in LOGGING["loggers"].values():
        logger["handlers"] = [h for h in logger.get("handlers", []) if h == "console"]
